import { mkdir, readFile, rename, writeFile } from "node:fs/promises";
import { dirname } from "node:path";
export type StoredConversationTurn = Readonly<{ turnId: string; userText: string; assistantText: string; createdAt: string }>;
export type ConversationRecord = Readonly<{ conversationId: string; turns: readonly StoredConversationTurn[] }>;
export interface ConversationMemoryStore { appendTurn(id: string, turn: StoredConversationTurn): Promise<void> | void; getConversation(id: string): Promise<ConversationRecord | undefined> | ConversationRecord | undefined; deleteConversation(id: string): Promise<boolean> | boolean; hasConversation(id: string): Promise<boolean> | boolean; }
export class ConversationMemoryPersistenceError extends Error { constructor(message: string) { super(message); this.name = "ConversationMemoryPersistenceError"; } }
const copy = (turn: StoredConversationTurn): StoredConversationTurn => Object.freeze({ ...turn });
const valid = (turn: unknown): turn is StoredConversationTurn => !!turn && typeof turn === "object" && typeof (turn as StoredConversationTurn).turnId === "string" && typeof (turn as StoredConversationTurn).userText === "string" && typeof (turn as StoredConversationTurn).assistantText === "string" && typeof (turn as StoredConversationTurn).createdAt === "string";
export class InMemoryConversationStore implements ConversationMemoryStore { protected readonly data = new Map<string, StoredConversationTurn[]>(); constructor(protected readonly maxConversations = 100, protected readonly maxTurns = 50) {} appendTurn(id: string, turn: StoredConversationTurn): void { if (!id.trim() || !valid(turn)) throw new ConversationMemoryPersistenceError("Invalid conversation turn."); let turns = this.data.get(id); if (!turns) { if (this.data.size >= this.maxConversations) this.data.delete(this.data.keys().next().value!); turns = []; this.data.set(id, turns); } turns.push(copy(turn)); if (turns.length > this.maxTurns) turns.splice(0, turns.length - this.maxTurns); } getConversation(id: string): ConversationRecord | undefined { const turns = this.data.get(id); return turns ? Object.freeze({ conversationId: id, turns: Object.freeze(turns.map(copy)) }) : undefined; } deleteConversation(id: string): boolean { return this.data.delete(id); } hasConversation(id: string): boolean { return this.data.has(id); } }
type Envelope = { version: 1; conversations: Record<string, StoredConversationTurn[]> };
/** Process-local file-backed store using serialized temp-file replacement; not horizontal-scale storage. */
export class FileConversationMemoryStore implements ConversationMemoryStore { private readonly memory: InMemoryConversationStore; private loaded = false; private writeChain: Promise<void> = Promise.resolve(); constructor(private readonly filePath: string, private readonly maxConversations = 100, private readonly maxTurns = 50) { this.memory = new InMemoryConversationStore(maxConversations, maxTurns); } private async load(): Promise<void> { if (this.loaded) return; try { const parsed: unknown = JSON.parse(await readFile(this.filePath, "utf8")); if (!parsed || typeof parsed !== "object" || (parsed as Envelope).version !== 1 || !((parsed as Envelope).conversations) || typeof (parsed as Envelope).conversations !== "object") throw new Error("schema"); for (const [id, turns] of Object.entries((parsed as Envelope).conversations)) { if (!id.trim() || !Array.isArray(turns) || !turns.every(valid)) throw new Error("schema"); for (const turn of turns.slice(-this.maxTurns)) this.memory.appendTurn(id, turn); } } catch (error) { if ((error as NodeJS.ErrnoException).code !== "ENOENT") throw new ConversationMemoryPersistenceError("Conversation memory persistence is corrupted or invalid."); } this.loaded = true; } private persist(): Promise<void> { this.writeChain = this.writeChain.then(async () => { const conversations: Record<string, StoredConversationTurn[]> = {}; for (const id of Array.from({ length: this.maxConversations }, (_, index) => index)) void id; const snapshot = this.memory as unknown as { data: Map<string, StoredConversationTurn[]> }; for (const [id, turns] of snapshot.data) conversations[id] = turns.map(copy); const temp = `${this.filePath}.tmp`; await mkdir(dirname(this.filePath), { recursive: true }); await writeFile(temp, JSON.stringify({ version: 1, conversations } satisfies Envelope), "utf8"); await rename(temp, this.filePath); }); return this.writeChain; } async appendTurn(id: string, turn: StoredConversationTurn): Promise<void> { await this.load(); this.memory.appendTurn(id, turn); await this.persist(); } async getConversation(id: string): Promise<ConversationRecord | undefined> { await this.load(); return this.memory.getConversation(id); } async deleteConversation(id: string): Promise<boolean> { await this.load(); const deleted = this.memory.deleteConversation(id); if (deleted) await this.persist(); return deleted; } async hasConversation(id: string): Promise<boolean> { await this.load(); return this.memory.hasConversation(id); } }
export const selectConversationContext = (record: ConversationRecord | undefined, maxTurns: number, maxChars: number): readonly StoredConversationTurn[] => { if (!record) return Object.freeze([]); const selected: StoredConversationTurn[] = []; let chars = 0; for (const turn of [...record.turns].reverse()) { const size = turn.userText.length + turn.assistantText.length; if (selected.length && chars + size > maxChars) break; selected.unshift(turn); chars += size; if (selected.length >= maxTurns) break; } return Object.freeze(selected.map(copy)); };
