import { Mic, Send, Square } from "lucide-react";
import type { KeyboardEvent } from "react";
import type { VoiceRuntimeState } from "../../types/voiceRuntimeState";

const stateCopy: Record<VoiceRuntimeState, string> = { idle: "Voz lista", listening: "Escuchando…", capturing: "Escuchando…", transcribing: "Transcribiendo…", thinking: "LUMI está pensando…", synthesizing: "Preparando voz…", speaking: "LUMI está hablando…", error: "Revisa la voz" };
const activeStates = new Set<VoiceRuntimeState>(["listening", "capturing", "transcribing", "thinking", "synthesizing", "speaking"]);
const bars = [3, 7, 12, 8, 16, 11, 20, 13, 7, 15, 9, 18, 10, 6, 13, 8, 4, 10, 6, 3];

type Props = { value: string; onChange: (value: string) => void; onSend: () => void; onVoiceAction: () => void; voiceState: VoiceRuntimeState; backendMode: boolean; disabled: boolean };

export const LumiVoiceComposer = ({ value, onChange, onSend, onVoiceAction, voiceState, backendMode, disabled }: Props) => {
  const active = activeStates.has(voiceState);
  const recording = voiceState === "listening" || voiceState === "capturing";
  const onKeyDown = (event: KeyboardEvent<HTMLTextAreaElement>) => { if (event.key === "Enter" && !event.shiftKey) { event.preventDefault(); onSend(); } };
  return <div data-voice-state={voiceState} className={`lumi-voice-dock relative border-t border-teal-200/10 p-3 transition duration-300 ${active ? "is-active bg-emerald-950/15" : "bg-slate-950/55"}`}>
    {active ? <div aria-live="polite" className="mb-3 flex items-center gap-3 rounded-2xl border border-emerald-300/15 bg-emerald-300/[0.04] px-4 py-3"><span className={`grid h-10 w-10 shrink-0 place-items-center rounded-full border ${recording ? "border-emerald-300/35 bg-emerald-300/15 text-emerald-200" : "border-cyan-300/25 bg-cyan-300/10 text-cyan-200"}`}><Mic className={`h-4 w-4 ${recording ? "animate-pulse" : ""}`} /></span><div className="min-w-0 flex-1"><p className="text-center text-xs font-semibold text-slate-100">{stateCopy[voiceState]}</p><div className="mt-2 flex h-6 items-center justify-center gap-1" aria-hidden="true">{bars.map((height, index) => <i key={`${height}-${index}`} className="lumi-wave-bar w-0.5 rounded-full bg-gradient-to-t from-cyan-400 to-emerald-300" style={{ height }} />)}</div></div>{recording ? <button type="button" onClick={onVoiceAction} className="grid h-10 w-10 shrink-0 place-items-center rounded-full border border-rose-300/30 bg-rose-400/10 text-rose-200 transition hover:bg-rose-400/20 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-rose-300" aria-label="Detener grabación de voz"><Square className="h-3.5 w-3.5" /></button> : null}</div> : null}
    <div className="flex min-h-[68px] items-end gap-2 rounded-[22px] border border-cyan-200/12 bg-gradient-to-br from-slate-900/90 to-slate-950/90 p-2 shadow-[inset_0_1px_rgba(207,250,254,0.035),0_18px_44px_rgba(0,8,22,0.3)] transition focus-within:border-cyan-300/30 focus-within:shadow-[inset_0_1px_rgba(207,250,254,0.05),0_14px_42px_rgba(34,211,238,0.08)]"><div className="min-w-0 flex-1 px-2 py-1"><textarea value={value} onChange={(event) => onChange(event.target.value)} onKeyDown={onKeyDown} aria-label="Mensaje para LUMI" placeholder="Escribe o habla con LUMI…" rows={1} className="w-full resize-none bg-transparent py-1 text-sm text-slate-100 placeholder-slate-500 outline-none" /><div className="flex justify-between text-[9px] text-slate-600"><span>Enter para enviar · Shift + Enter para salto</span><span>{backendMode ? "Local" : "Demo"}</span></div></div><button type="button" onClick={onVoiceAction} disabled={disabled || (!backendMode && !recording)} className={`grid h-11 w-11 shrink-0 place-items-center rounded-full border transition focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-violet-300 disabled:opacity-35 ${recording ? "border-rose-300/40 bg-rose-400/15 text-rose-100" : "border-emerald-300/20 bg-emerald-300/10 text-emerald-100 hover:scale-[1.03] hover:bg-emerald-300/20"}`} aria-label={recording ? "Detener grabación de voz" : "Iniciar mensaje de voz para LUMI"}><Mic className="h-4 w-4" /></button><button type="button" onClick={onSend} disabled={!value.trim() || disabled} className="grid h-11 w-11 shrink-0 place-items-center rounded-full border border-cyan-200/20 bg-gradient-to-br from-cyan-400 to-teal-600 text-white shadow-[0_8px_24px_rgba(13,148,136,0.24)] transition hover:scale-[1.03] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-cyan-200 disabled:opacity-35" aria-label="Enviar mensaje a LUMI"><Send className="h-4 w-4" /></button></div>
  </div>;
};
