export type ProviderUsage=Readonly<{inputTokens?:number;outputTokens?:number;cacheReadTokens?:number;cacheWriteTokens?:number}>;
import type { RuntimeDispositionCategory, RuntimeFailureReasonCode } from "../types/runtimeFailureSemantics.js";
export type TelemetryEvent=Readonly<{eventId:string;eventType:"CONVERSATION_TURN"|"PROVIDER_CALL"|"TOOL_EXECUTION"|"RUNTIME_ERROR"|"RUNTIME_DISPOSITION";timestamp:string;internalConversationId?:string;durationMs?:number;success?:boolean;errorCode?:string;provider?:string;model?:string;toolName?:string;usage?:ProviderUsage;runtimeDisposition?:RuntimeDispositionCategory;reasonCode?:RuntimeFailureReasonCode;profileId?:string;configurationFingerprint?:string}>;
export interface TelemetrySink{record(event:TelemetryEvent):void;snapshot():readonly TelemetryEvent[];clear():void}
export class BoundedInMemoryTelemetrySink implements TelemetrySink{private events:TelemetryEvent[]=[];constructor(private readonly capacity=100){}record(event:TelemetryEvent){this.events.push(Object.freeze({...event,usage:event.usage?Object.freeze({...event.usage}):undefined}));if(this.events.length>this.capacity)this.events.shift()}snapshot(){return Object.freeze(this.events.map(e=>Object.freeze({...e,usage:e.usage?Object.freeze({...e.usage}):undefined})))}clear(){this.events=[]}}
export const recordTelemetry=(sink:TelemetrySink|undefined,event:TelemetryEvent):void=>{try{sink?.record(event)}catch{/* telemetry is best effort */}};
export type PricingEntry=Readonly<{provider:string;model:string;currency:"USD";inputPerMillion:number;outputPerMillion:number;catalogVersion:string}>;
export class PricingCatalog{constructor(private readonly entries:readonly PricingEntry[]=[]){ }find(provider:string,model:string){return this.entries.find(x=>x.provider===provider&&x.model===model)}}
export const estimateCost=(usage:ProviderUsage|undefined,entry:PricingEntry|undefined):Readonly<{state:"KNOWN"|"UNKNOWN";microunits?:number}>=>{if(!usage||usage.inputTokens===undefined||usage.outputTokens===undefined||!entry)return{state:"UNKNOWN"};return{state:"KNOWN",microunits:Math.round((usage.inputTokens*entry.inputPerMillion+usage.outputTokens*entry.outputPerMillion)/1_000_000*1_000_000)}};
export const runtimeAnalytics=(events:readonly TelemetryEvent[])=>{const turns=events.filter(e=>e.eventType==="CONVERSATION_TURN"),providers=events.filter(e=>e.eventType==="PROVIDER_CALL"),tools=events.filter(e=>e.eventType==="TOOL_EXECUTION"),lat=providers.map(e=>e.durationMs??0);return Object.freeze({totalCompletedTurns:turns.length,successfulTurns:turns.filter(e=>e.success).length,failedTurns:turns.filter(e=>e.success===false).length,providerCalls:providers.length,toolCalls:tools.length,toolSuccesses:tools.filter(e=>e.success).length,toolFailures:tools.filter(e=>e.success===false).length,averageLatencyMs:lat.length?lat.reduce((a,b)=>a+b,0)/lat.length:0})};
